### ISSUE TITLE
Push notifikacia na Firefoxe? :-[

### ISSUE THREAD

**Issue by bubooo** [slovensko-help/vaccination-notify#2]
Nastavil som si Push notifikaciu pre Volne miesta vo Firefoxe. Ked som povolil, tak som dostal chybovu hlasku, ze sa to nepodarilo. Ked som to skusil 2x, tak zahlasil, ze uz mam nastavenu notifikaciu.
Screenshoty som zabudol v soku z takejto appky :)

Firefox 86
Linux Mint

**Comment by J08nY** [comment]
Hmm, nejaké percento odberov PUSH notifikácii zlyháva, neviem moc zistiť prečo, Firefox robí dosť problémov. Bohužiaľ nemám moc kapacity to fixovať a snoriť kde a prečo a v ktorom Firefoxe to nejde. Pozriem sa na to ale neočakávam fix.

**Comment by bubooo** [comment]
Ok. Mozno ma zmysel napisat ti na stranku. Chrome funguje?

Pekny den praje
Lubo Bucko

Dňa po 8. 3. 2021, 13:54 Ján Jančár <notifications@github.com> napísal(a):

**Comment by J08nY** [comment]
Ono sa taketo veci stavaju proste v urcitom malom mnozstve pripadov, vidim to na [sentry.io](https://sentry.io) logoch, nechcem o kazdom z tychto problemov pisat lebo to viac menej len zmatie ludi.

Chromium/Chrome by mal fungovat ohladom PUSH notifikacii lepsie ako Firefox ano. Konkretne problem z tejto issue by nemal nastat.

**Comment by bubooo** [comment]
Nastavit to islo na Chrome. Len som nedostal notifikaciu. 😊
Len sa zamyslam, ci vcerajsi pruser s vypadkom webu nemali na svedomi aj
taketo aplikacie, ked NCZI servre nezvladali tolko api requestov 😇. Lebo
minimalne tato sa celkom sirila ...

Dňa po 8. 3. 2021, 14:01 Ján Jančár <notifications@github.com> napísal(a):

**Comment by stanop** [comment]
Na Chrome mobilnom mi pushka prisla ale neskoro. Zrejme problem na server side.

**Comment by J08nY** [comment]
Jo, vcera vecer bol obrovsky load, pribudli miesta a sluzba sa snazila odoslat 30k emailov a 7k pushiek cca, to nejde az tak rychlo. Respektive, je tam jedna known performance issue ktoru musim vyriesit a pojde to rychlejsie. Kazdopadne aj tak poslanie 30k emailov (bez Mailgunu alebo podobnej sluzby) za par minut je trochu moc a musim silno optimalizovat sluzbu, na co nemam momentalne cas a energiu.
![Screenshot from 2021-03-09 10-29-14](https://user-images.githubusercontent.com/1296726/110449322-60254c80-80c2-11eb-8a22-4dd439684fba.png)

**Comment by marki555** [comment]
> 
> Nastavit to islo na Chrome. Len som nedostal notifikaciu. 😊 Len sa zamyslam, ci vcerajsi pruser s vypadkom webu nemali na svedomi aj taketo aplikacie, ked NCZI servre nezvladali tolko api requestov 😇. Lebo minimalne tato sa celkom sirila ...

Predpokladam ze pocet API requestov z tejto stranky je rovnaky bez ohladu na pocet jej uzivatelov. A nech je takychto stranok (aj sukromnych) 10-20, tak je to stale nic v porovnani s tisickami ludi co nonstop refreshuju ten formular lebo sa to nevie nacitat... lebo to pre kazdeho musi nacitavat 100 kB json (vcera vecer ho nacitavalo tak 30-100 sekund s tym ze minimalne v 50% pripadov ich server proste spojenie zahodil), ktory obsahuje pre kazde ockovacie miesto a pre kazdy datum osobitne info o volnych miestach a pritom tieto informacie nikoho nezaujimaju (ked som z BA nepotrebujem vediet ze nemocnica X v Piestanoch bude mat zajtra Y a pozajtra Z miest, staci mi sumarne cislo za kazdy kraj a nasledne detailne info pre kraj co si vyberiem). Ale to by tam niekto musel rozmyslat :)
Ale ano, vypadok webu mala na svedomi aj tato aplikacia, lebo sa ludia dozvedeli o novych terminoch nielen z Facebooku ministra ale aj zo svojho emailu :) A samozrejme reach tych FB postov a ich naslednych zdielani je urcite za pol hodinu vacsi ako tychto 30-40k ludi co to ma nastavene cez tuto stranku.

**Comment by michalbali256** [comment]
> Respektive, je tam jedna known performance issue ktoru musim vyriesit a pojde to rychlejsie.

Keby si ten issue popisal, niekto by ti mozne vyrobil PR co to fixne. (:
Alebo precenujem silu open source :D

V kazdom pripade vdaka za cool sluzbu, uspesne sme vdaka tomu prihlasili dedka...

**Comment by J08nY** [comment]
Perf issue je v vacnotify/query/tasks.py a konkrétne v tom ako sa používa SQLAlchemy ORM na https://github.com/slovensko-help/vaccination-notify/blob/79278962b0de25807af68239370876f985d5caf8/vacnotify/tasks/query.py#L307-L323.  Pre každú subscription ktorej sa majú aktualizovať `known_cities`, čo je zoznam miest o ktorých voľných miestach sa robí transakcia čo robí `commit` tej Session v SQLAlchemy ORM a ten commit práve expiruje všetky objekty vytiahnuté z DB a tým pádom sa query robí znova a objekty sa ťahajú znova. Celkovo runtime tejto run task proste nepekne narastá. Tá task je periodická a keď sa teda už stane že sa spustí druhá tak to už úplne zomiera.

Chcem to prerobiť na to, že run task bude robiť iba queries a vytvárať notifikačné tasky (možno po batchoch) a už notifikačné tasky samotné budú robiť zmeny v DB a teda tie budú mať transakcie a nebude treba potom ťahať tak veľa objektov zase.

Neočakávam tu nejakú silnú pomoc open-source, je to môj bordel toto a tak si ho aj upracem. Chcelo by to niekoho čo robí SQLAlchemy dosť a aj celery aby mi to prekopal.

**Comment by J08nY** [comment]
Kedze uz je sluzba vypnuta uzatvaram issue.
