### ISSUE TITLE
V email správe chýba link na zrušenie odberu notifikácií

### ISSUE THREAD

**Issue by vlm---** [slovensko-help/vaccination-notify#4]
Zdravím, v notifikačnej email správe o termínoch chýba link na zrušenie odberu notifikácií.

**Comment by J08nY** [comment]
Email o termínoch na 9.3. bol odosielaný prakticky manuálne a na poslednú chvíľu (viď aa9a2efd9a08c42b835b2d2f28e00c01a5cc0e17 ) a tak neobsahoval unsubscribe link ako bežné notifikačné emaily. Tie ho vždy majú.

Pridám ale možnosť nechať si poslať email s unsubscribe linkom alebo prípadne editovanie nastavených miest.
